# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e83a9556e660f96f8a5a258d3396d45f948f0c4d74e9432bf85e9a9ecaf3a7d7af78c84aad5df4fa6db0f1f44b8f82cf67f71d8e7d7b70db4db5f2d0048b0d1d

test:
  secret_key_base: 5455284a877ae6f109889cbd27d8298199246938e8359d792500294175644fe7b849f7ffae5850e5a8e5701125f90aacbf504e705ebbddcb746385abece062fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
